name: Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-java@v3.1.1
      with:
       java-version: 17
       distribution: 'zulu'
    - uses: actions/checkout@v3
    - run: |
       gradlew.bat build
       pwd
      shell: cmd
    - uses: svenstaro/upload-release-action@v2
      with:
       repo_token: ${{ secrets.GITHUB_TOKEN }}
       file: build/libs
